name: Google Cloud Continuous Deployment - Staging site

on:
  push:
    branches: [ cd-staging-setup ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
      - run: npm run prod

      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.STAGING_GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.STAGING_GCP_SA_KEY }}
          project_id: ${{ secrets.STAGING_PROJECT_ID }}

      - name: Publish app to Google App Engine
        run: |
          gcloud auth activate-service-account ${{ secrets.STAGING_GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.STAGING_PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote