name: Test Selenium GithubAction

on:
  push:
    branches: [ nicko/test-rename-periphs ]

jobs:
  test_selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run prod